#!/bin/zsh

vim_cmd=`whence -p vim`

cross_realpath() (
    if [ -x "$(command -v realpath)" ]; then
        echo `realpath $1`
    else
        local orig_dir=$PWD
        cd "$(dirname "$1")"
        local real_path="$PWD/$(basename "$1")"
        cd "$orig_dir"
        echo "$real_path"
    fi
)

ipc_vim() {
    if [[ $full_file_path =~ '^\/.*$' ]]; then
        local full_file_path=`cross_realpath $1`
    else
        local full_file_path=$1
    fi
    local sock_name=$2
    local cmd=$3
    local line=$4
    echo $line $full_file_path $cmd | nc -U ${VIM9_NOX11_SOCK_DIR}/${sock_name}.sock
}

alt_vim() {
    local cmd="/e"
    local line="+0"
    for arg in "$@"; do
        if [[ $arg =~ '^\+[0-9]+' ]]; then
            line=$arg
        elif [[ $arg == "/v" ]]; then
            cmd="/v"
        elif [[ $arg == "/t" ]]; then
            cmd="/t"
        elif [[ $arg == "/e" ]]; then
            cmd="/e"
        else
            local file=$arg
        fi
    done

    if [[ ! -z $file ]]; then
        ipc_vim $file ${VIM9_NOX11_VIMSERVER} $cmd $line
        if [[ -z $VIM_TERMINAL ]]; then
            exit
        fi
    else
        echo "No new session allowed from vim terminal"
    fi
}

if [[ "$@" =~ '^.*\/COMMIT_EDITMSG$' ]]; then
    VIM9_NOX11_VIMSERVER='' $vim_cmd $@
elif [[ -z $VIM9_NOX11_VIMSERVER ]]; then
    VIM9_NOX11_VIMSERVER=VIM`date +%s` $vim_cmd $@
else
    alt_vim $@
fi
